version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: social-media-db
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: social_media_platform
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-puser"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: social-media-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/social_media_platform
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend-network
      - frontend-network
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: social-media-frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:8080/api/v1
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - frontend-network
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local