spring:
  application:
    name: social-media-platform

  datasource:
    url: jdbc:mysql://localhost:3306/social_media_platform?useSSL=false
    username: root
    password: user

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  web:
    resources:
      static-locations: file:uploads/

storage:
  upload-dir: uploads


recaptcha:
  secret: 6Lf9jbMqAAAAAD7_g3n9H4-NmXw52Cffl-NCCKrI